[project]
name = "cypher"
version = "1.0.0"
description = "A valorant Discord bot"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorthief>=0.2.1",
    "discord-py>=2.6.4",
    "dotenv>=0.9.9",
    "requests>=2.32.5",
]
