[project]
name = "cypher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "colorthief>=0.2.1",
    "discord>=2.3.2",
    "dotenv>=0.9.9",
    "requests>=2.32.5",
]
